version: '3'

services:
  keycloak:
    image: keycloak:build
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_WELCOME_THEME: bcy
    volumes:
      - ./bcy:/opt/jboss/keycloak/themes/bcy
      - ./base:/opt/jboss/keycloak/themes/base